//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DFC.Integration.AVFeed.Service.AVSoapAPI.FAA
{


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacancySearchData", Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1")]
    [System.SerializableAttribute()]
    public partial class VacancySearchData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> VacancyReferenceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OccupationCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FrameworkCodeField;
        
        private DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailsSearchLocationType VacancyLocationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegionCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> VacancyPublishedDateField;
        
        private int PageIndexField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> VacancyReferenceId {
            get {
                return this.VacancyReferenceIdField;
            }
            set {
                if ((this.VacancyReferenceIdField.Equals(value) != true)) {
                    this.VacancyReferenceIdField = value;
                    this.RaisePropertyChanged("VacancyReferenceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string OccupationCode {
            get {
                return this.OccupationCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.OccupationCodeField, value) != true)) {
                    this.OccupationCodeField = value;
                    this.RaisePropertyChanged("OccupationCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string FrameworkCode {
            get {
                return this.FrameworkCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.FrameworkCodeField, value) != true)) {
                    this.FrameworkCodeField = value;
                    this.RaisePropertyChanged("FrameworkCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailsSearchLocationType VacancyLocationType {
            get {
                return this.VacancyLocationTypeField;
            }
            set {
                if ((this.VacancyLocationTypeField.Equals(value) != true)) {
                    this.VacancyLocationTypeField = value;
                    this.RaisePropertyChanged("VacancyLocationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string CountyCode {
            get {
                return this.CountyCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyCodeField, value) != true)) {
                    this.CountyCodeField = value;
                    this.RaisePropertyChanged("CountyCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string RegionCode {
            get {
                return this.RegionCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.RegionCodeField, value) != true)) {
                    this.RegionCodeField = value;
                    this.RaisePropertyChanged("RegionCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<System.DateTime> VacancyPublishedDate {
            get {
                return this.VacancyPublishedDateField;
            }
            set {
                if ((this.VacancyPublishedDateField.Equals(value) != true)) {
                    this.VacancyPublishedDateField = value;
                    this.RaisePropertyChanged("VacancyPublishedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacancyDetailsSearchLocationType", Namespace="http://schemas.datacontract.org/2004/07/Capgemini.LSC.Navms.MS.Common.Enums")]
    public enum VacancyDetailsSearchLocationType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NonNational = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        National = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacancyDetailResponseData", Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1")]
    [System.SerializableAttribute()]
    public partial class VacancyDetailResponseData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.WebInterfaceGenericDetailsData AVMSHeaderField;
        
        private DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyFullData[] SearchResultsField;
        
        private int TotalPagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.WebInterfaceGenericDetailsData AVMSHeader {
            get {
                return this.AVMSHeaderField;
            }
            set {
                if ((object.ReferenceEquals(this.AVMSHeaderField, value) != true)) {
                    this.AVMSHeaderField = value;
                    this.RaisePropertyChanged("AVMSHeader");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyFullData[] SearchResults {
            get {
                return this.SearchResultsField;
            }
            set {
                if ((object.ReferenceEquals(this.SearchResultsField, value) != true)) {
                    this.SearchResultsField = value;
                    this.RaisePropertyChanged("SearchResults");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int TotalPages {
            get {
                return this.TotalPagesField;
            }
            set {
                if ((this.TotalPagesField.Equals(value) != true)) {
                    this.TotalPagesField = value;
                    this.RaisePropertyChanged("TotalPages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WebInterfaceGenericDetailsData", Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1")]
    [System.SerializableAttribute()]
    public partial class WebInterfaceGenericDetailsData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ApprenticeshipVacanciesDescriptionField;
        
        private string ApprenticeshipVacanciesURLField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ApprenticeshipVacanciesDescription {
            get {
                return this.ApprenticeshipVacanciesDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprenticeshipVacanciesDescriptionField, value) != true)) {
                    this.ApprenticeshipVacanciesDescriptionField = value;
                    this.RaisePropertyChanged("ApprenticeshipVacanciesDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string ApprenticeshipVacanciesURL {
            get {
                return this.ApprenticeshipVacanciesURLField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprenticeshipVacanciesURLField, value) != true)) {
                    this.ApprenticeshipVacanciesURLField = value;
                    this.RaisePropertyChanged("ApprenticeshipVacanciesURL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacancyFullData", Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1")]
    [System.SerializableAttribute()]
    public partial class VacancyFullData : DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancySummaryData {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContactPersonField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContractOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DeliveryOrganisationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployerDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployerWebsiteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExpectedDurationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FutureProspectsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InterviewFromDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<bool> IsDisplayRecruitmentAgencyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsSmallEmployerWageIncentiveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LearningProviderDescField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> LearningProviderSectorPassRateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtherImportantInformationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PersonalQualitiesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PossibleStartDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string QualificationRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SkillsRequiredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplementaryQuestion1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplementaryQuestion2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TrainingToBeProvidedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VacancyManagerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VacancyOwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> WageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WageTextField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.WageType WageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkingWeekField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContactPerson {
            get {
                return this.ContactPersonField;
            }
            set {
                if ((object.ReferenceEquals(this.ContactPersonField, value) != true)) {
                    this.ContactPersonField = value;
                    this.RaisePropertyChanged("ContactPerson");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ContractOwner {
            get {
                return this.ContractOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.ContractOwnerField, value) != true)) {
                    this.ContractOwnerField = value;
                    this.RaisePropertyChanged("ContractOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DeliveryOrganisation {
            get {
                return this.DeliveryOrganisationField;
            }
            set {
                if ((object.ReferenceEquals(this.DeliveryOrganisationField, value) != true)) {
                    this.DeliveryOrganisationField = value;
                    this.RaisePropertyChanged("DeliveryOrganisation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerDescription {
            get {
                return this.EmployerDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployerDescriptionField, value) != true)) {
                    this.EmployerDescriptionField = value;
                    this.RaisePropertyChanged("EmployerDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerWebsite {
            get {
                return this.EmployerWebsiteField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployerWebsiteField, value) != true)) {
                    this.EmployerWebsiteField = value;
                    this.RaisePropertyChanged("EmployerWebsite");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExpectedDuration {
            get {
                return this.ExpectedDurationField;
            }
            set {
                if ((object.ReferenceEquals(this.ExpectedDurationField, value) != true)) {
                    this.ExpectedDurationField = value;
                    this.RaisePropertyChanged("ExpectedDuration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullDescription {
            get {
                return this.FullDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.FullDescriptionField, value) != true)) {
                    this.FullDescriptionField = value;
                    this.RaisePropertyChanged("FullDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FutureProspects {
            get {
                return this.FutureProspectsField;
            }
            set {
                if ((object.ReferenceEquals(this.FutureProspectsField, value) != true)) {
                    this.FutureProspectsField = value;
                    this.RaisePropertyChanged("FutureProspects");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InterviewFromDate {
            get {
                return this.InterviewFromDateField;
            }
            set {
                if ((this.InterviewFromDateField.Equals(value) != true)) {
                    this.InterviewFromDateField = value;
                    this.RaisePropertyChanged("InterviewFromDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsDisplayRecruitmentAgency {
            get {
                return this.IsDisplayRecruitmentAgencyField;
            }
            set {
                if ((this.IsDisplayRecruitmentAgencyField.Equals(value) != true)) {
                    this.IsDisplayRecruitmentAgencyField = value;
                    this.RaisePropertyChanged("IsDisplayRecruitmentAgency");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSmallEmployerWageIncentive {
            get {
                return this.IsSmallEmployerWageIncentiveField;
            }
            set {
                if ((this.IsSmallEmployerWageIncentiveField.Equals(value) != true)) {
                    this.IsSmallEmployerWageIncentiveField = value;
                    this.RaisePropertyChanged("IsSmallEmployerWageIncentive");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LearningProviderDesc {
            get {
                return this.LearningProviderDescField;
            }
            set {
                if ((object.ReferenceEquals(this.LearningProviderDescField, value) != true)) {
                    this.LearningProviderDescField = value;
                    this.RaisePropertyChanged("LearningProviderDesc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LearningProviderSectorPassRate {
            get {
                return this.LearningProviderSectorPassRateField;
            }
            set {
                if ((this.LearningProviderSectorPassRateField.Equals(value) != true)) {
                    this.LearningProviderSectorPassRateField = value;
                    this.RaisePropertyChanged("LearningProviderSectorPassRate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtherImportantInformation {
            get {
                return this.OtherImportantInformationField;
            }
            set {
                if ((object.ReferenceEquals(this.OtherImportantInformationField, value) != true)) {
                    this.OtherImportantInformationField = value;
                    this.RaisePropertyChanged("OtherImportantInformation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PersonalQualities {
            get {
                return this.PersonalQualitiesField;
            }
            set {
                if ((object.ReferenceEquals(this.PersonalQualitiesField, value) != true)) {
                    this.PersonalQualitiesField = value;
                    this.RaisePropertyChanged("PersonalQualities");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PossibleStartDate {
            get {
                return this.PossibleStartDateField;
            }
            set {
                if ((this.PossibleStartDateField.Equals(value) != true)) {
                    this.PossibleStartDateField = value;
                    this.RaisePropertyChanged("PossibleStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QualificationRequired {
            get {
                return this.QualificationRequiredField;
            }
            set {
                if ((object.ReferenceEquals(this.QualificationRequiredField, value) != true)) {
                    this.QualificationRequiredField = value;
                    this.RaisePropertyChanged("QualificationRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SkillsRequired {
            get {
                return this.SkillsRequiredField;
            }
            set {
                if ((object.ReferenceEquals(this.SkillsRequiredField, value) != true)) {
                    this.SkillsRequiredField = value;
                    this.RaisePropertyChanged("SkillsRequired");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplementaryQuestion1 {
            get {
                return this.SupplementaryQuestion1Field;
            }
            set {
                if ((object.ReferenceEquals(this.SupplementaryQuestion1Field, value) != true)) {
                    this.SupplementaryQuestion1Field = value;
                    this.RaisePropertyChanged("SupplementaryQuestion1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplementaryQuestion2 {
            get {
                return this.SupplementaryQuestion2Field;
            }
            set {
                if ((object.ReferenceEquals(this.SupplementaryQuestion2Field, value) != true)) {
                    this.SupplementaryQuestion2Field = value;
                    this.RaisePropertyChanged("SupplementaryQuestion2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrainingToBeProvided {
            get {
                return this.TrainingToBeProvidedField;
            }
            set {
                if ((object.ReferenceEquals(this.TrainingToBeProvidedField, value) != true)) {
                    this.TrainingToBeProvidedField = value;
                    this.RaisePropertyChanged("TrainingToBeProvided");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VacancyManager {
            get {
                return this.VacancyManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.VacancyManagerField, value) != true)) {
                    this.VacancyManagerField = value;
                    this.RaisePropertyChanged("VacancyManager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VacancyOwner {
            get {
                return this.VacancyOwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.VacancyOwnerField, value) != true)) {
                    this.VacancyOwnerField = value;
                    this.RaisePropertyChanged("VacancyOwner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Wage {
            get {
                return this.WageField;
            }
            set {
                if ((this.WageField.Equals(value) != true)) {
                    this.WageField = value;
                    this.RaisePropertyChanged("Wage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WageText {
            get {
                return this.WageTextField;
            }
            set {
                if ((object.ReferenceEquals(this.WageTextField, value) != true)) {
                    this.WageTextField = value;
                    this.RaisePropertyChanged("WageText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.WageType WageType {
            get {
                return this.WageTypeField;
            }
            set {
                if ((this.WageTypeField.Equals(value) != true)) {
                    this.WageTypeField = value;
                    this.RaisePropertyChanged("WageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkingWeek {
            get {
                return this.WorkingWeekField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkingWeekField, value) != true)) {
                    this.WorkingWeekField = value;
                    this.RaisePropertyChanged("WorkingWeek");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VacancySummaryData", Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyFullData))]
    public partial class VacancySummaryData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApprenticeshipFrameworkField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime ClosingDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CreatedDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LearningProviderNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int NumberOfPositionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ShortDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.AddressData VacancyAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VacancyLocationTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int VacancyReferenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VacancyTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VacancyTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VacancyUrlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApprenticeshipFramework {
            get {
                return this.ApprenticeshipFrameworkField;
            }
            set {
                if ((object.ReferenceEquals(this.ApprenticeshipFrameworkField, value) != true)) {
                    this.ApprenticeshipFrameworkField = value;
                    this.RaisePropertyChanged("ApprenticeshipFramework");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime ClosingDate {
            get {
                return this.ClosingDateField;
            }
            set {
                if ((this.ClosingDateField.Equals(value) != true)) {
                    this.ClosingDateField = value;
                    this.RaisePropertyChanged("ClosingDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CreatedDateTime {
            get {
                return this.CreatedDateTimeField;
            }
            set {
                if ((this.CreatedDateTimeField.Equals(value) != true)) {
                    this.CreatedDateTimeField = value;
                    this.RaisePropertyChanged("CreatedDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployerName {
            get {
                return this.EmployerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployerNameField, value) != true)) {
                    this.EmployerNameField = value;
                    this.RaisePropertyChanged("EmployerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LearningProviderName {
            get {
                return this.LearningProviderNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LearningProviderNameField, value) != true)) {
                    this.LearningProviderNameField = value;
                    this.RaisePropertyChanged("LearningProviderName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumberOfPositions {
            get {
                return this.NumberOfPositionsField;
            }
            set {
                if ((this.NumberOfPositionsField.Equals(value) != true)) {
                    this.NumberOfPositionsField = value;
                    this.RaisePropertyChanged("NumberOfPositions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShortDescription {
            get {
                return this.ShortDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ShortDescriptionField, value) != true)) {
                    this.ShortDescriptionField = value;
                    this.RaisePropertyChanged("ShortDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.AddressData VacancyAddress {
            get {
                return this.VacancyAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.VacancyAddressField, value) != true)) {
                    this.VacancyAddressField = value;
                    this.RaisePropertyChanged("VacancyAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VacancyLocationType {
            get {
                return this.VacancyLocationTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VacancyLocationTypeField, value) != true)) {
                    this.VacancyLocationTypeField = value;
                    this.RaisePropertyChanged("VacancyLocationType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VacancyReference {
            get {
                return this.VacancyReferenceField;
            }
            set {
                if ((this.VacancyReferenceField.Equals(value) != true)) {
                    this.VacancyReferenceField = value;
                    this.RaisePropertyChanged("VacancyReference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VacancyTitle {
            get {
                return this.VacancyTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.VacancyTitleField, value) != true)) {
                    this.VacancyTitleField = value;
                    this.RaisePropertyChanged("VacancyTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VacancyType {
            get {
                return this.VacancyTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.VacancyTypeField, value) != true)) {
                    this.VacancyTypeField = value;
                    this.RaisePropertyChanged("VacancyType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VacancyUrl {
            get {
                return this.VacancyUrlField;
            }
            set {
                if ((object.ReferenceEquals(this.VacancyUrlField, value) != true)) {
                    this.VacancyUrlField = value;
                    this.RaisePropertyChanged("VacancyUrl");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AddressData", Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1")]
    [System.SerializableAttribute()]
    public partial class AddressData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string AddressLine1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AddressLine5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GridEastMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> GridNorthMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<decimal> LongitudeField;
        
        private string PostCodeField;
        
        private string TownField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocalAuthorityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string AddressLine1 {
            get {
                return this.AddressLine1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine1Field, value) != true)) {
                    this.AddressLine1Field = value;
                    this.RaisePropertyChanged("AddressLine1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine2 {
            get {
                return this.AddressLine2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine2Field, value) != true)) {
                    this.AddressLine2Field = value;
                    this.RaisePropertyChanged("AddressLine2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine3 {
            get {
                return this.AddressLine3Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine3Field, value) != true)) {
                    this.AddressLine3Field = value;
                    this.RaisePropertyChanged("AddressLine3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine4 {
            get {
                return this.AddressLine4Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine4Field, value) != true)) {
                    this.AddressLine4Field = value;
                    this.RaisePropertyChanged("AddressLine4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AddressLine5 {
            get {
                return this.AddressLine5Field;
            }
            set {
                if ((object.ReferenceEquals(this.AddressLine5Field, value) != true)) {
                    this.AddressLine5Field = value;
                    this.RaisePropertyChanged("AddressLine5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string County {
            get {
                return this.CountyField;
            }
            set {
                if ((object.ReferenceEquals(this.CountyField, value) != true)) {
                    this.CountyField = value;
                    this.RaisePropertyChanged("County");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GridEastM {
            get {
                return this.GridEastMField;
            }
            set {
                if ((this.GridEastMField.Equals(value) != true)) {
                    this.GridEastMField = value;
                    this.RaisePropertyChanged("GridEastM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> GridNorthM {
            get {
                return this.GridNorthMField;
            }
            set {
                if ((this.GridNorthMField.Equals(value) != true)) {
                    this.GridNorthMField = value;
                    this.RaisePropertyChanged("GridNorthM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<decimal> Longitude {
            get {
                return this.LongitudeField;
            }
            set {
                if ((this.LongitudeField.Equals(value) != true)) {
                    this.LongitudeField = value;
                    this.RaisePropertyChanged("Longitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string PostCode {
            get {
                return this.PostCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.PostCodeField, value) != true)) {
                    this.PostCodeField = value;
                    this.RaisePropertyChanged("PostCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Town {
            get {
                return this.TownField;
            }
            set {
                if ((object.ReferenceEquals(this.TownField, value) != true)) {
                    this.TownField = value;
                    this.RaisePropertyChanged("Town");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public string LocalAuthority {
            get {
                return this.LocalAuthorityField;
            }
            set {
                if ((object.ReferenceEquals(this.LocalAuthorityField, value) != true)) {
                    this.LocalAuthorityField = value;
                    this.RaisePropertyChanged("LocalAuthority");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WageType", Namespace="http://schemas.datacontract.org/2004/07/Capgemini.LSC.Navms.MS.Common.Enum")]
    public enum WageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Text = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Weekly = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SystemFaultContract", Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1")]
    [System.SerializableAttribute()]
    public partial class SystemFaultContract : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1", ConfigurationName="FAA.IVacancyDetails")]
    public interface IVacancyDetails {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.imservices.org.uk/AVMS/Interfaces/5.1/IVacancyDetails/Get", ReplyAction="http://services.imservices.org.uk/AVMS/Interfaces/5.1/IVacancyDetails/GetResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.SystemFaultContract), Action="http://services.imservices.org.uk/AVMS/Interfaces/5.1/IVacancyDetails/GetSystemFa" +
            "ultContractFault", Name="SystemFaultContract")]
        DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailsResponse Get(DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailsRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.imservices.org.uk/AVMS/Interfaces/5.1/IVacancyDetails/Get", ReplyAction="http://services.imservices.org.uk/AVMS/Interfaces/5.1/IVacancyDetails/GetResponse" +
            "")]
        System.Threading.Tasks.Task<DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailsResponse> GetAsync(DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VacancyDetailsRequest", WrapperNamespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1", IsWrapped=true)]
    public partial class VacancyDetailsRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1")]
        public System.Guid ExternalSystemId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1")]
        public System.Guid MessageId;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1")]
        public string PublicKey;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1", Order=0)]
        public DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancySearchData VacancySearchCriteria;
        
        public VacancyDetailsRequest() {
        }
        
        public VacancyDetailsRequest(System.Guid ExternalSystemId, System.Guid MessageId, string PublicKey, DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancySearchData VacancySearchCriteria) {
            this.ExternalSystemId = ExternalSystemId;
            this.MessageId = MessageId;
            this.PublicKey = PublicKey;
            this.VacancySearchCriteria = VacancySearchCriteria;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="VacancyDetailsResponse", WrapperNamespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1", IsWrapped=true)]
    public partial class VacancyDetailsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1", Order=0)]
        public System.Guid MessageId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.imservices.org.uk/AVMS/Interfaces/5.1", Order=1)]
        public DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailResponseData SearchResults;
        
        public VacancyDetailsResponse() {
        }
        
        public VacancyDetailsResponse(System.Guid MessageId, DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailResponseData SearchResults) {
            this.MessageId = MessageId;
            this.SearchResults = SearchResults;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IVacancyDetailsChannel : DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.IVacancyDetails, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VacancyDetailsClient : System.ServiceModel.ClientBase<DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.IVacancyDetails>, DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.IVacancyDetails {
        
        public VacancyDetailsClient() {
        }
        
        public VacancyDetailsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VacancyDetailsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VacancyDetailsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VacancyDetailsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailsResponse DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.IVacancyDetails.Get(DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailsRequest request) {
            return base.Channel.Get(request);
        }
        
        public DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailResponseData Get(System.Guid ExternalSystemId, ref System.Guid MessageId, string PublicKey, DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancySearchData VacancySearchCriteria) {
            DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailsRequest inValue = new DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailsRequest();
            inValue.ExternalSystemId = ExternalSystemId;
            inValue.MessageId = MessageId;
            inValue.PublicKey = PublicKey;
            inValue.VacancySearchCriteria = VacancySearchCriteria;
            DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailsResponse retVal = ((DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.IVacancyDetails)(this)).Get(inValue);
            MessageId = retVal.MessageId;
            return retVal.SearchResults;
        }
        
        public System.Threading.Tasks.Task<DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailsResponse> GetAsync(DFC.Integration.AVFeed.Service.AVSoapAPI.FAA.VacancyDetailsRequest request) {
            return base.Channel.GetAsync(request);
        }
    }
}
